# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: "Set OS distribution dependent variables"
  ansible.builtin.include_vars: "{{ ansible_facts.distribution }}.yml"

- name: "Perform prerequisite checks"
  ansible.builtin.import_tasks: "check.yml"

- name: "Reconfigure GitLab"
  ansible.builtin.import_tasks: "reconfigure.yml"
  become: true
  when: "__gitlab_reconfigure_failed.stat.exists"

- name: "Install GitLab"
  ansible.builtin.import_tasks: "install.yml"
  become: true

- name: "Configure GitLab"
  ansible.builtin.import_tasks: "configure.yml"
  become: true

- name: "Check if GitLab is already configured"
  ansible.builtin.stat:
    path: "/opt/gitlab/etc/gitlab-rails-rc"
  register: "__gitlab_rails_rc"

- name: "Force all notified handlers to run at this point. Required for feature flags."
  ansible.builtin.meta: "flush_handlers"
  when:
    - "not __gitlab_rails_rc.stat.exists"
    - "gitlab_feature_flags | length > 0"

- name: "Set feature flags"
  ansible.builtin.include_tasks: "feature-flag.yml"
  loop: "{{ gitlab_feature_flags }}"
  loop_control:
    loop_var: "gitlab_feature_flag"

...
