# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: "Check if fleeting-plugin-openstack is installed"
  ansible.builtin.stat:
    path: "/usr/local/bin/fleeting-plugin-openstack"
  register: "__fleeting_plugin_openstack_stat"

- name: "Check version of installed fleeting plugin"
  when: "__fleeting_plugin_openstack_stat.stat.exists"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      strings /usr/local/bin/fleeting-plugin-openstack | grep -oP "(?<=fleeting-plugin-openstack.Version=)(\d+\.\d+\.\d+)" | head -n 1
    executable: "/bin/bash"
  register: "__fleeting_plugin_version_installed"
  changed_when: false
  check_mode: false

- name: "Download and install fleeting plugin"
  when: "not __fleeting_plugin_openstack_stat.stat.exists or __fleeting_plugin_version_installed.stdout != gitlab_runner_autoscaler_binary_version"
  block:
    - name: "Create temporary directory"
      ansible.builtin.tempfile:
        state: "directory"
      register: "__tempdir_fleeting_plugin"
      check_mode: false
      changed_when: false

    - name: "Download fleeting-plugin-openstack"
      ansible.builtin.get_url:
        url: "{{ gitlab_runner_autoscaler_plugin_url }}"
        dest: "{{ (__tempdir_fleeting_plugin.path, 'fleeting-plugin-openstack.tar.gz') | path_join }}"
        checksum: "sha512:{{ gitlab_runner_autoscaler_plugin_checksumfile }}"
        owner: "root"
        group: "root"
        mode: "0600"
      check_mode: false

    - name: "Extract fleeting-plugin-openstack binary"
      ansible.builtin.unarchive:
        src: "{{ (__tempdir_fleeting_plugin.path, 'fleeting-plugin-openstack.tar.gz') | path_join }}"
        dest: "/usr/local/bin/"
        include:
          - "bin/fleeting-plugin-openstack"
        owner: "root"
        group: "root"
        mode: "0755"
        remote_src: true
        extra_opts: ['--strip-components=1']

  always:
    - name: "Remove temporary directory"
      ansible.builtin.file:
        path: "{{ __tempdir_fleeting_plugin.path }}"
        state: "absent"
      check_mode: false
      changed_when: false

- name: "Place clouds.yaml template"
  ansible.builtin.template:
    src: "clouds.yaml.j2"
    dest: "/etc/gitlab-runner/clouds.yaml"
    owner: "root"
    group: "root"
    mode: '0600'
  no_log: "{{ gitlab_runner_hide_sensitive_changes }}"

...
