# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: MIT

---

- name: "Configure Zammad repository for Centos-like"
  when: "ansible_facts.distribution | lower == 'centos'"
  block:

    - name: "Install | Install EPEL repo"
      ansible.builtin.dnf:
        name: "epel-release"
        state: "present"

    - name: "Install | Add Zammad yum repository"
      ansible.builtin.yum_repository:
        name: "zammad"
        state: "present"
        description: "Repository for zammad/zammad ({{ zammad_release_channel }}) packages."
        baseurl: "https://dl.packager.io/srv/rpm/zammad/zammad/{{ zammad_release_channel }}/el/7/$basearch"
        enabled: true
        gpgcheck: false
        repo_gpgcheck: true
        gpgkey: "https://dl.packager.io/srv/zammad/zammad/key"
        mode: "0644"

- name: "Configure Zammad repository for Ubuntu"
  when: "ansible_facts.distribution | lower == 'ubuntu'"
  block:

    - name: "Remove Zammad apt key from legacy trusted.gpg keyring"
      ansible.builtin.apt_key:
        url: "https://dl.packager.io/srv/zammad/zammad/key"
        state: "absent"

    - name: "Remove Zammad DEB repository from sources.list"
      ansible.builtin.apt_repository:
        repo: "deb https://dl.packager.io/srv/deb/zammad/zammad/{{ zammad_release_channel }}/ubuntu {{ ansible_facts.distribution_version }} main"
        state: "absent"
        filename: "zammad"
        update_cache: false

    - name: "Install | Add Zammad DEB repository"
      ansible.builtin.deb822_repository:
        name: "zammad"
        types: "deb"
        uris: "{{ zammad_repo_url }}"
        suites: "{{ ansible_facts.distribution_version }}"
        components: "main"
        signed_by: "https://dl.packager.io/srv/zammad/zammad/key"
        architectures: "amd64"
        state: "present"
        mode: "0644"
        enabled: true

    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

- name: "Gather the package facts to check wether Zammad has already been installed"
  ansible.builtin.package_facts:
    manager: "auto"

- name: "Check if Zammad is already installed"
  ansible.builtin.set_fact:
    __zammad_is_installed: "{{ 'zammad' in ansible_facts.packages }}"

- name: "Install | Install Zammad package"
  ansible.builtin.package:
    name: "zammad={{ zammad_version }}*"
    state: "present"
    force: true
  notify:
    - "Set Elasticsearch server address"
    - "Build search index"

- name: "Install | Start and enable services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: "started"
    enabled: true
  loop:
    - "zammad"
    - "zammad-web"
    - "zammad-worker"
    - "zammad-websocket"
  notify: "Build search index"

...
