# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: MIT

---
zammad_version: "6.5.0"
zammad_release_channel: "stable"
zammad_repo_url: "https://dl.packager.io/srv/deb/zammad/zammad/{{ zammad_release_channel }}/{{ ansible_facts.distribution | lower }}"
zammad_domain_name: "{{ ansible_facts.fqdn }}"

zammad_nginx_config_path: "/etc/nginx/sites-available/zammad.conf"
zammad_ssl_cert_path: "/etc/ssl/certs/zammad_cert.pem"
zammad_ssl_key_path: "/etc/ssl/private/zammad_key.pem"

zammad_nginx_additional_server_configs: []
zammad_nginx_server_tokens: "off"

zammad_force_es_searchindex_rebuild: false

zammad_elasticsearch_url: "http://localhost:9200"
...
