# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
dependency:
  name: "galaxy"
driver:
  name: "podman"
platforms:
  - name: "instancegitlab"
    image: "${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:24.04}"
    pre_build_image: true
    privileged: true
    systemd: "always"
    tty: true
    override_command: false
provisioner:
  name: "ansible"
  config_options:
    defaults:
      result_format: "yaml"
  playbooks:
    prepare: "prepare.yml"
    check: "converge.yml"
    converge: "converge.yml"
    verify: "verify.yml"
  inventory:
    host_vars:
      instancegitlab:
        gitlab_edition: "gitlab-ce"
        gitlab_ip_range: "0.0.0.0/0"
        gitlab_additional_configurations:
          - package:
              - key: "modify_kernel_parameters"
                type: "plain"
                value: "false"
          - gitlab_kas:
              - key: "env"
                type: "plain"
                value: "{ 'OWN_PRIVATE_API_URL' => 'grpc://127.0.0.1:8155' }"
          - registry:
              - key: "database"
                type: "plain"
                value: |-
                  {
                    'enabled' => false,
                    'host' => '{{ gitlab_postgresql_db_host }}',
                    'port' => {{ gitlab_postgresql_db_port }},
                    'user' => 'gitlab',
                    'password' => '{{ gitlab_postgresql_db_password }}',
                    'dbname' => 'registry',
                    'sslmode' => 'disable'
                  }
        gitlab_feature_flags:
          # See https://docs.gitlab.com/ee/user/feature_flags.html
          - name: "vscode_web_ide"
            enabled: true
          - name: "chatops"
            enabled: true
          - name: "webauthn"
            enabled: false
verifier:
  name: "ansible"
scenario:
  name: "gitlab"
  test_sequence:
    - "destroy"
    - "dependency"
    - "syntax"
    - "create"
    - "prepare"
    - "check"
    - "converge"
    - "idempotence"
    - "check"
    - "side_effect"
    - "verify"
    - "destroy"

...
