# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Release new version on Ansible Galaxy"

on:
  release:
    types:
      - "released"

jobs:

  release:
    name: "Release new version on Ansible Galaxy"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v5"

      - name: "Deploy the collection"
        uses: "artis3n/ansible_galaxy_collection@v2.11.0"
        with:
          api_key: "${{ secrets.galaxy_api_key }}"
