# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
name: "hifis.toolkit.unattended_upgrades"

on:
  pull_request:
    paths:
      - '.github/workflows/unattended_upgrades.yml'
      - '.github/workflows/prepare-action/action.yml'
      - 'roles/unattended_upgrades/**'
      - 'molecule/unattended_upgrades/**'
      - 'pyproject.toml'
      - 'uv.lock'
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
    paths:
      - '.github/workflows/unattended_upgrades.yml'
      - '.github/workflows/prepare-action/action.yml'
      - 'roles/unattended_upgrades/**'
      - 'molecule/unattended_upgrades/**'
      - 'pyproject.toml'
      - 'uv.lock'
  schedule:
    - cron: '0 0 * * *'

jobs:

  test:
    name: "Run Molecule tests."
    runs-on: "ubuntu-24.04"
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        image:
          - "ghcr.io/hifis-net/ubuntu-systemd:22.04"
          - "ghcr.io/hifis-net/ubuntu-systemd:24.04"
          - "ghcr.io/hifis-net/debian-systemd:12"
          - "ghcr.io/hifis-net/debian-systemd:11"

    steps:
      - name: "Check out the codebase."
        uses: "actions/checkout@v5"
        with:
          path: "./ansible_collections/hifis/toolkit"

      - name: "Prepare the job environment."
        uses: "./ansible_collections/hifis/toolkit/.github/workflows/prepare-action"

      - name: "Run Molecule tests."
        run: "uv run molecule test -s unattended_upgrades"
        env:
          MOLECULE_IMAGE: "${{ matrix.image }}"
        working-directory: "./ansible_collections/hifis/toolkit"
